data = [
    ("What is the weather like today?", "query"),
    ("Show me the latest news.", "query"),
    ("How are you?", "query"),
    ("What's the time?", "query"),
    ("Find the nearest restaurant.", "query"),
    ("Who won the game last night?", "query"),
    ("What's the capital of France?", "query"),
    ("Tell me a joke.", "query"),
    ("Play some music.", "query"),
    ("What's the traffic like right now?", "query"),
    ("How do I make a reservation?", "query"),
    ("What's the stock price of Apple?", "query"),
    ("Translate 'hello' to Spanish.", "query"),
    ("What's the latest movie?", "query"),
    ("How far is the moon?", "query"),
    ("Recommend a good book.", "query"),
    ("What's the meaning of life?", "query"),
    ("Set an alarm for 7 AM.", "query"),
    ("What's 2+2?", "query"),
    ("Show me my calendar.", "query"),
    ("When is the next holiday?", "query"),
    ("What is AI?", "query"),
    ("Find a coffee shop nearby.", "query"),
    ("How tall is Mount Everest?", "query"),
    ("What is the population of New York?", "query"),
    ("What's on my to-do list?", "query"),
    ("Remind me to call mom.", "query"),
    ("What time is sunset?", "query"),
    ("What's the best route to the airport?", "query"),
    ("Show me a picture of a cat.", "query"),
    ("Who is the President of the United States?", "query"),
    ("What's the latest technology news?", "query"),
    ("How do I get to the nearest hospital?", "query"),
    ("What's the best restaurant in town?", "query"),
    ("What is the speed of light?", "query"),
    ("Show me my messages.", "query"),
    ("What's the recipe for pancakes?", "query"),
    ("Who invented the telephone?", "query"),
    ("Tell me the news.", "query"),
    ("What's the population of Tokyo?", "query"),
    ("What's the highest-grossing movie?", "query"),
    ("How do I change a tire?", "query"),
    ("What's the largest ocean?", "query"),
    ("What's the distance to Mars?", "query"),
    ("What's the current temperature?", "query"),
    ("What time is it in London?", "query"),
    ("What's the definition of 'serendipity'?", "query"),
    ("How do I bake a cake?", "query"),
    ("What are the symptoms of a cold?", "query"),
    ("What's the currency of Japan?", "query"),
    ("What's the best way to learn Python?", "query"),
    ("Show me the weather forecast.", "query"),
    ("What's the capital of Australia?", "query"),
    ("How many continents are there?", "query"),
    ("Who wrote '1984'?", "query"),
    ("What's the population of India?", "query"),
    ("What's the largest planet in our solar system?", "query"),
    ("How do I tie a tie?", "query"),
    ("What's the square root of 64?", "query"),
    ("How do I get to the city center?", "query"),
    ("What's the fastest animal on land?", "query"),
    ("What's the smallest country?", "query"),
    ("What's the current exchange rate for USD to EUR?", "query"),
    ("What's the capital of Italy?", "query"),
    ("Who won the World Cup?", "query"),
    ("What's the longest river in the world?", "query"),
    ("What's the national dish of Spain?", "query"),
    ("How do I improve my English?", "query"),
    ("What's the time difference between New York and Tokyo?", "query"),
    ("What is quantum computing?", "query"),
    ("Show me the top news stories.", "query"),
    ("Who is the CEO of Google?", "query"),
    ("What's the weather like in Paris?", "query"),
    ("What's the highest mountain in Africa?", "query"),
    ("How do I get a passport?", "query"),
    ("What's the speed limit in California?", "query"),
    ("What's the most populated city in the world?", "query"),
    ("Who is the author of 'Harry Potter'?", "query"),
    ("What's the tallest building in the world?", "query"),
    ("What's the latest fashion trend?", "query"),
    ("How do I start a business?", "query"),
    ("What's the most popular tourist destination?", "query"),
    ("What's the formula for water?", "query"),
    ("What's the average salary in the US?", "query"),
    ("How do I lose weight?", "query"),
    ("What's the capital of Canada?", "query"),
    ("What's the name of the longest river?", "query"),
    ("How do I apply for a visa?", "query"),
    ("What's the population of Brazil?", "query"),
    ("What's the best way to travel to Europe?", "query"),
    ("Who painted the Mona Lisa?", "query"),
    ("What's the current gold price?", "query"),
    ("What's the best way to invest money?", "query"),
    ("What's the population of China?", "query"),
    ("What's the time in Sydney?", "query"),
    ("How do I cook pasta?", "query"),
    ("What's the capital of Germany?", "query"),
    ("What's the highest temperature ever recorded?", "query"),
    ("What's the most spoken language in the world?", "query"),
    ("How do I buy a house?", "query"),
    ("What's the population of Russia?", "query"),
    ("What are the best places to visit in Italy?", "query"),
    ("What's the best programming language?", "query"),
    ("How do I create a website?", "query"),
    ("What's the best workout routine?", "query"),
    ("Who discovered electricity?", "query"),
    ("What's the average lifespan of a human?", "query"),
    ("How do I cancel my subscription?", "query"),
    ("What's the tallest waterfall?", "query"),
    ("What is climate change?", "query"),
    ("Who was Albert Einstein?", "query"),
    ("What's the largest desert?", "query"),
    ("How do I improve my credit score?", "query"),
    ("What's the most expensive car?", "query"),
    ("What is cryptocurrency?", "query"),
    ("How do I make a phone call?", "query"),
    ("What's the best way to learn a new language?", "query"),
    ("What is photosynthesis?", "query"),
    ("Who is the richest person in the world?", "query"),
    ("What's the longest book ever written?", "query"),
    ("How do I get a job?", "query"),
    ("What's the meaning of 'deja vu'?", "query"),
    ("What's the capital of Mexico?", "query"),
    ("What's the population of Australia?", "query"),
    ("How do I fix a leaky faucet?", "query"),
    ("What's the best way to save money?", "query"),
    ("Who was the first person on the moon?", "query"),
    ("What's the name of the tallest mountain?", "query"),
    ("How do I write a resume?", "query"),
    ("What's the best way to clean windows?", "query"),
    ("What's the capital of Argentina?", "query"),
    ("What's the best way to study for an exam?", "query"),
    ("How do I make an omelet?", "query"),
    ("What's the time in Tokyo?", "query"),
    ("What's the fastest car in the world?", "query"),
    ("Who invented the internet?", "query"),
    ("What's the best way to get rid of a headache?", "query"),
    ("What's the tallest building in the US?", "query"),
    ("How do I find my IP address?", "query"),
    ("What's the population of South Africa?", "query"),
    ("How do I register to vote?", "query"),
    ("What's the best way to learn math?", "query"),
    ("What's the capital of Brazil?", "query"),
    ("What's the best way to organize a closet?", "query"),
    ("What's the best way to travel to Asia?", "query"),
    ("Who wrote 'Pride and Prejudice'?", "query"),
    ("What's the current silver price?", "query"),
    ("What's the best way to invest in real estate?", "query"),
    ("What's the population of Nigeria?", "query"),
    ("What's the time in Berlin?", "query"),
    ("How do I boil an egg?", "query"),
    ("What's the capital of Egypt?", "query"),
    ("What's the coldest temperature ever recorded?", "query"),
    ("What's the most widely spoken language?", "query"),
    ("How do I rent an apartment?", "query"),
    ("What's the population of the UK?", "query"),
    ("What are the best places to visit in Japan?", "query"),
    ("What's the best programming language for beginners?", "query"),
    ("How do I create a blog?", "query"),
    ("What's the best exercise for weight loss?", "query"),
    ("Who invented the airplane?", "query"),
    ("What's the average lifespan of a dog?", "query"),
    ("How do I delete my account?", "query"),
    ("What's the largest waterfall?", "query"),
    ("What is the greenhouse effect?", "query"),
    ("Who was Isaac Newton?", "query"),
    ("What's the largest forest?", "query"),
    ("How do I improve my memory?", "query"),
    ("What's the most expensive painting?", "query"),
    ("What is blockchain technology?", "query"),
    ("How do I send a text message?", "query"),
    ("What's the best way to learn a musical instrument?", "query"),
    ("What is mitosis?", "query"),
    ("Who is the wealthiest person in history?", "query"),
    ("What's the longest movie ever made?", "query"),
    ("How do I write a cover letter?", "query"),
    ("What's the meaning of 'karma'?", "query"),
    ("What's the capital of Chile?", "query"),
    ("What's the population of New Zealand?", "query"),
    ("How do I fix a clogged drain?", "query"),
    ("What's the best way to budget?", "query"),
    ("Who was the first woman in space?", "query"),
    ("What's the name of the deepest ocean?", "query"),
    ("How do I format a hard drive?", "query"),
    ("What's the tallest mountain in North America?", "query"),
    ("How do I write a business plan?", "query"),
    ("What's the best way to clean carpets?", "query"),
    ("What's the capital of Peru?", "query"),
    ("What's the best way to prepare for a job interview?", "query"),
    ("How do I make spaghetti?", "query"),
    ("What's the time in Beijing?", "query"),
    ("What's the fastest train in the world?", "query"),
    ("Who invented the light bulb?", "query"),
    ("What's the best way to relieve stress?", "query"),
    ("What's the tallest building in Europe?", "query"),
    ("How do I find my MAC address?", "query"),
    ("What's the population of Kenya?", "query"),
    ("How do I apply for a driver's license?", "query"),
    ("What's the best way to learn science?", "query"),
    ("What's the capital of Colombia?", "query"),
    ("What's the best way to organize a kitchen?", "query"),
    ("What's the best way to travel to South America?", "query"),
    ("Who wrote 'To Kill a Mockingbird'?", "query"),
    ("What's the current platinum price?", "query"),
    ("What's the best way to invest in stocks?", "query"),
    ("What's the population of Indonesia?", "query"),
    ("What's the time in Moscow?", "query"),
    ("How do I grill a steak?", "query"),
    ("What's the capital of Saudi Arabia?", "query"),
    ("What's the hottest temperature ever recorded?", "query"),
    ("What's the most common language in Europe?", "query"),
    ("How do I buy a car?", "query"),
    ("What's the population of France?", "query"),
    ("What are the best places to visit in Canada?", "query"),
    ("What's the best programming language for web development?", "query"),
    ("How do I create a podcast?", "query"),
    ("What's the best exercise for building muscle?", "query"),
    ("Who discovered penicillin?", "query"),
    ("What's the average lifespan of a cat?", "query"),
    ("How do I reset my password?", "query"),
    ("What's the largest island?", "query"),
    ("What is global warming?", "query"),
    ("Who was Nikola Tesla?", "query"),
    ("What's the largest lake?", "query"),
    ("How do I increase my productivity?", "query"),
    ("What's the most valuable gemstone?", "query"),
    ("What is 5G technology?", "query"),
    ("How do I make a video call?", "query"),
    ("What's the best way to learn photography?", "query"),
    ("What is meiosis?", "query"),
    ("Who is the wealthiest woman in the world?", "query"),
    ("What's the longest running TV show?", "query"),
    ("How do I write a thank you note?", "query"),
    ("What's the meaning of 'nirvana'?", "query"),
    ("What's the capital of Norway?", "query"),
    ("What's the population of Switzerland?", "query"),
    ("How do I fix a broken screen?", "query"),
    ("What's the best way to save for retirement?", "query"),
    ("Who was the first person to climb Mount Everest?", "query"),
    ("What's the name of the smallest ocean?", "query"),
    ("How do I upgrade my computer?", "query"),
    ("What's the tallest mountain in Europe?", "query"),
    ("How do I write a press release?", "query"),
    ("What's the best way to clean a bathroom?", "query"),
    ("What's the capital of Venezuela?", "query"),
    ("What's the best way to prepare for a presentation?", "query"),
    ("How do I make lasagna?", "query"),
    ("What's the time in Hong Kong?", "query"),
    ("What's the fastest plane in the world?", "query"),
    ("Who invented the computer?", "query"),
    ("What's the best way to deal with anxiety?", "query"),
    ("What's the tallest building in Asia?", "query"),
    ("How do I find my router's IP address?", "query"),
    ("What's the population of Turkey?", "query"),
    ("How do I renew my passport?", "query"),
    ("What's the best way to learn history?", "query"),
    ("What's the capital of South Korea?", "query"),
    ("What's the best way to organize a garage?", "query"),
    ("What's the best way to travel to Africa?", "query"),
    ("Who wrote 'The Great Gatsby'?", "query"),
    ("What's the current copper price?", "query"),
    ("What's the best way to invest in bonds?", "query"),
    ("What's the population of Pakistan?", "query"),
    ("What's the time in Dubai?", "query"),
    ("How do I bake cookies?", "query"),
    ("What's the capital of Thailand?", "query"),
    ("What's the most humid place on Earth?", "query"),
    ("What's the most common language in Asia?", "query"),
    ("How do I lease a car?", "query"),
    ("What's the population of Italy?", "query"),
    ("What are the best places to visit in Australia?", "query"),
    ("What's the best programming language for data science?", "query"),
    ("How do I create an online course?", "query"),
    ("What's the best exercise for flexibility?", "query"),
    ("Who discovered gravity?", "query"),
    ("What's the average lifespan of a parrot?", "query"),
    ("How do I deactivate my account?", "query"),
    ("What's the largest peninsula?", "query"),
    ("What is ocean acidification?", "query"),
    ("Who was Marie Curie?", "query"),
    ("What's the largest archipelago?", "query"),
    ("How do I manage my time effectively?", "query"),
    ("What's the rarest metal?", "query"),
    ("What is virtual reality?", "query"),
    ("How do I make a conference call?", "query"),
    ("What's the best way to learn painting?", "query"),
    ("What is DNA replication?", "query"),
    ("Who is the youngest billionaire?", "query"),
    ("What's the longest play ever performed?", "query"),
    ("How do I write a business email?", "query"),
    ("What's the meaning of 'feng shui'?", "query"),
    ("What's the capital of Portugal?", "query"),
    ("What's the population of Sweden?", "query"),
    ("How do I repair a flat tire?", "query"),
    ("What's the best way to build an emergency fund?", "query"),
    ("Who was the first woman to win a Nobel Prize?", "query"),
    ("What's the name of the shallowest sea?", "query"),
    ("How do I upgrade my phone?", "query"),
    ("What's the tallest mountain in South America?", "query"),
    ("How do I write a blog post?", "query"),
    ("What's the best way to clean a kitchen?", "query"),
    ("What's the capital of Finland?", "query"),
    ("What's the best way to prepare for a meeting?", "query"),
    ("How do I make a smoothie?", "query"),
    ("What's the time in Mumbai?", "query"),
    ("What's the fastest ship in the world?", "query"),
    ("Who invented the printing press?", "query"),
    ("What's the best way to cope with depression?", "query"),
    ("What's the tallest building in the Middle East?", "query"),
    ("How do I find my laptop's MAC address?", "query"),
    ("What's the population of Argentina?", "query"),
    ("How do I apply for a loan?", "query"),
    ("What's the best way to learn geography?", "query"),
    ("What's the capital of Malaysia?", "query"),
    ("What's the best way to organize a basement?", "query"),
    ("What's the best way to travel to North America?", "query"),
    ("Who wrote 'Moby Dick'?", "query"),
    ("What's the current palladium price?", "query"),
    ("What's the best way to invest in mutual funds?", "query"),
    ("What's the population of Bangladesh?", "query"),
    ("What's the time in Johannesburg?", "query"),
    ("How do I fry an egg?", "query"),
    ("What's the capital of the Philippines?", "query"),
    ("What's the wettest place on Earth?", "query"),
    ("What's the most common language in Africa?", "query"),
    ("How do I finance a car?", "query"),
    ("What's the population of Spain?", "query"),
    ("What are the best places to visit in South America?", "query"),
    ("What's the best programming language for AI?", "query"),
    ("How do I create a mobile app?", "query"),
    ("What's the best exercise for endurance?", "query"),
    ("Who discovered radioactivity?", "query"),
    ("What's the average lifespan of a turtle?", "query"),
    ("How do I block a number?", "query"),
    ("What's the largest plateau?", "query"),
    ("What is deforestation?", "query"),
    ("Who was Galileo Galilei?", "query"),
    ("What's the largest coral reef?", "query"),
    ("How do I boost my immune system?", "query"),
    ("What's the most expensive watch?", "query"),
    ("What is augmented reality?", "query"),
    ("How do I make a group call?", "query"),
    ("What's the best way to learn sculpting?", "query"),
    ("What is cell division?", "query"),
    ("Who is the richest athlete?", "query"),
    ("What's the longest song ever recorded?", "query"),
    ("How do I write a thank you email?", "query"),
    ("What's the meaning of 'samsara'?", "query"),
    ("What's the capital of Greece?", "query"),
    ("What's the population of Denmark?", "query"),
    ("How do I fix a broken zipper?", "query"),
    ("What's the best way to invest in precious metals?", "query"),
    ("Who was the first person to reach the North Pole?", "query"),
    ("What's the name of the deepest lake?", "query"),
    ("How do I upgrade my software?", "query"),
    ("What's the tallest mountain in Antarctica?", "query"),
    ("How do I write an essay?", "query"),
    ("What's the best way to clean a bedroom?", "query"),
    ("What's the capital of Hungary?", "query"),
    ("What's the best way to prepare for a test?", "query"),
    ("How do I make guacamole?", "query"),
    ("What's the time in Shanghai?", "query"),
    ("What's the fastest bicycle in the world?", "query"),
    ("Who invented the telephone?", "query"),
    ("What's the best way to handle stress?", "query"),
    ("What's the tallest building in Africa?", "query"),
    ("How do I find my ISP?", "query"),
    ("What's the population of Poland?", "query"),
    ("How do I open a bank account?", "query"),
    ("What's the best way to learn physics?", "query"),
    ("What's the capital of the Netherlands?", "query"),
    ("What's the best way to organize a home office?", "query"),
    ("What's the best way to travel to Oceania?", "query"),
    ("Who wrote 'War and Peace'?", "query"),
    ("What's the current nickel price?", "query"),
    ("What's the best way to invest in ETFs?", "query"),
    ("What's the population of Egypt?", "query"),
    ("What's the time in Rio de Janeiro?", "query"),
    ("How do I bake a cake?", "query"),
    ("What's the capital of Vietnam?", "query"),
    ("What's the driest place on Earth?", "query"),
    ("What's the most common language in the Americas?", "query"),
    ("How do I finance a house?", "query"),
    ("What's the population of Saudi Arabia?", "query"),
    ("What are the best places to visit in the Middle East?", "query"),
    ("What's the best programming language for mobile development?", "query"),
    ("How do I create a YouTube channel?", "query"),
    ("What's the best exercise for balance?", "query"),
    ("Who discovered the electron?", "query"),
    ("What's the average lifespan of a rabbit?", "query"),
    ("How do I change my email password?", "query"),
    ("What's the largest island in the Mediterranean?", "query"),
    ("What is biodiversity?", "query"),
    ("Who was Thomas Edison?", "query"),
    ("What's the largest canyon?", "query"),
    ("How do I improve my mental health?", "query"),
    ("What's the most valuable coin?", "query"),
    ("What is nanotechnology?", "query"),
    ("How do I make a conference call on Zoom?", "query"),
    ("What's the best way to learn drawing?", "query"),
    ("What is genetic engineering?", "query"),
    ("Who is the richest actor?", "query"),
    ("What's the longest running musical?", "query"),
    ("How do I write a resignation letter?", "query"),
    ("What's the meaning of 'nirvana'?", "query"),
    ("What's the capital of Finland?", "query"),
    ("What's the population of Belgium?", "query"),
    ("How do I fix a broken window?", "query"),
    ("What's the best way to invest in cryptocurrencies?", "query"),
    ("Who was the first person to reach the South Pole?", "query"),
    ("What's the name of the largest sea?", "query"),
    ("How do I upgrade my antivirus?", "query"),
    ("What's the tallest mountain in North America?", "query"),
    ("How do I write a research paper?", "query"),
    ("What's the best way to clean a living room?", "query"),
    ("What's the capital of Austria?", "query"),
    ("What's the best way to prepare for a speech?", "query"),
    ("How do I make a burrito?", "query"),
    ("What's the time in Seoul?", "query"),
    ("What's the fastest motorcycle in the world?", "query"),
    ("Who invented the wheel?", "query"),
    ("What's the best way to cope with loneliness?", "query"),
    ("What's the tallest building in Australia?", "query"),
    ("How do I find my DNS server?", "query"),
    ("What's the population of Norway?", "query"),
    ("How do I apply for a scholarship?", "query"),
    ("What's the best way to learn biology?", "query"),
    ("What's the capital of Ireland?", "query"),
    ("What's the best way to organize a pantry?", "query"),
    ("What's the best way to travel to Antarctica?", "query"),
    ("Who wrote 'Great Expectations'?", "query"),
    ("What's the current zinc price?", "query"),
    ("What's the best way to invest in index funds?", "query"),
    ("What's the population of Iran?", "query"),
    ("What's the time in Buenos Aires?", "query"),
    ("How do I roast a chicken?", "query"),
    ("What's the capital of Morocco?", "query"),
    ("What's the rainiest place on Earth?", "query"),
    ("What's the most common language in Oceania?", "query"),
    ("How do I lease an apartment?", "query"),
    ("What's the population of South Korea?", "query"),
    ("What are the best places to visit in Africa?", "query"),
    ("What's the best programming language for backend development?", "query"),
    ("How do I create a WordPress site?", "query"),
    ("What's the best exercise for strength?", "query"),
    ("Who discovered the neutron?", "query"),
    ("What's the average lifespan of a hamster?", "query"),
    ("How do I change my Facebook password?", "query"),
    ("What's the largest island in the Caribbean?", "query"),
    ("What is sustainable development?", "query"),
    ("Who was Sigmund Freud?", "query"),
    ("What's the largest glacier?", "query"),
    ("How do I improve my concentration?", "query"),
    ("What's the most valuable stamp?", "query"),
    ("What is artificial intelligence?", "query"),
    ("How do I make a Skype call?", "query"),
    ("What's the best way to learn pottery?", "query"),
    ("What is gene therapy?", "query"),
    ("Who is the richest musician?", "query"),
    ("What's the longest running soap opera?", "query"),
    ("How do I write an obituary?", "query"),
    ("What's the meaning of 'moksha'?", "query"),
    ("What's the capital of Romania?", "query"),
    ("What's the population of Czech Republic?", "query"),
    ("How do I fix a broken chair?", "query"),
    ("What's the best way to invest in commodities?", "query"),
    ("Who was the first person to circumnavigate the globe?", "query"),
    ("What's the name of the saltiest lake?", "query"),
    ("How do I upgrade my RAM?", "query"),
    ("What's the tallest mountain in New Zealand?", "query"),
    ("How do I write a dissertation?", "query"),
    ("What's the best way to clean a dining room?", "query"),
    ("What's the capital of Bulgaria?", "query"),
    ("What's the best way to prepare for an interview?", "query"),
    ("How do I make a salad?", "query"),
    ("What's the time in Manila?", "query"),
    ("What's the fastest rocket in the world?", "query"),
    ("Who invented the radio?", "query"),
    ("What's the best way to manage stress?", "query"),
    ("What's the tallest building in the UK?", "query"),
    ("How do I find my gateway address?", "query"),
    ("What's the population of Finland?", "query"),
    ("How do I apply for unemployment benefits?", "query"),
    ("What's the best way to learn chemistry?", "query"),
    ("What's the capital of Poland?", "query"),
    ("What's the best way to organize a laundry room?", "query"),
    ("What's the best way to travel to the Arctic?", "query"),
    ("Who wrote 'The Odyssey'?", "query"),
    ("What's the current cobalt price?", "query"),
    ("What's the best way to invest in real estate?", "query"),
    ("What's the population of Turkey?", "query"),
    ("What's the time in Cape Town?", "query"),
    ("How do I bake bread?", "query"),
    ("What's the capital of Cambodia?", "query"),
    ("What's the foggiest place on Earth?", "query"),
    ("What's the most common language in the world?", "query"),
    ("How do I finance an education?", "query"),
    ("What's the population of North Korea?", "query"),
    ("What are the best places to visit in Europe?", "query")
]
